# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc1WRr8T8901fk1l2EHZhqX9aIXVvI77
"""

import random

def guess_the_number():
    print("Raqamni taxmin qil o'yiniga xush kelibsiz!")
    secret_number = random.randint(1, 100)  # 1 dan 100 gacha tasodifiy raqam
    attempts = 0

    while True:
        try:
            guess = int(input("1 dan 100 gacha raqamni kiritishingizni so'raymiz: "))
            attempts += 1

            if guess < 1 or guess > 100:
                print("Iltimos, 1 dan 100 gacha raqam kiriting.")
                continue

            if guess < secret_number:
                print("Kichik! Yana harakat qilib ko'ring.")
            elif guess > secret_number:
                print("Katta! Yana harakat qilib ko'ring.")
            else:
                print(f"Tabriklaymiz! Siz {attempts}-ta urinishda raqamni topdingiz: {secret_number}.")
                break
        except ValueError:
            print("Iltimos, raqam kiritishingiz kerak.")

# Dastur chiqishini ishga tushiramiz
guess_the_number()